# SPDX-FileCopyrightText: The dolt-installer Authors
# SPDX-License-Identifier: 0BSD

name: test-dolt-installer
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test-using-defaults:
    name: Using Defaults on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dolt
      uses: ./
    - name: Verify Installation
      run: dolt version
    - name: Check root directory
      shell: bash
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi
  test-using-custom-installer-directory:
    name: Custom Installer Directory on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dolt
        uses: ./
        with:
          install-directory: "$HOME/.dolttest"
      - name: Verify Installation
        run: dolt version
      - name: Check Installation Directory
        shell: bash
        run: |
          [[ $(dirname "$(which dolt)") == "$HOME/.dolttest" ]]
      - name: Check root directory
        shell: bash
        run: |
          [[ -z $(git diff --stat) ]]
